HtmlHelperTr/Models/Formulario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.ModelBinding;

namespace HtmlHelperTr.Models
{
    public class Formulario
    {
        [Required]
        public String Cedula { get; set; }
        [Required]
        public String Nombre { get; set; }
        [Required]
        public String Apellido { get; set; }
        [Required,Range(15,99)]
        public int Edad { get; set; }
        public String Telefono { get; set; }
        [Required,DataType(DataType.EmailAddress),EmailAddress]
        public String Correo { get; set; }
        public String Genero { get; set; }
        public String Estado { get; set; }
        public bool Hobbys { get; set; }

    }



    public enum Gender {
        Masculino,
        Femenino
    }
}

HtmlHelperTr/Controllers/FormularioController.cs
using HtmlHelperTr.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HtmlHelperTr.Controllers
{
    public class FormularioController : Controller
    {
        // GET: Formulario
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index( Formulario formulario)
        {
            if (ModelState.IsValid)
            {
                
                return View("Detalle", formulario);
            }
            else {
                return View(formulario);
            }

            
        }

        public ActionResult Detalle() {
            return View();
        }
    }
}

HtmlHelperTr/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HtmlHelperTr.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HtmlHelperTr/Views/Formulario/Detalle.cshtml
@model HtmlHelperTr.Models.Formulario

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    @Html.LabelFor(model=>model.Cedula) @Html.DisplayFor(model=>model.Cedula)<br />
    @Html.LabelFor(model=>model.Nombre) @Html.DisplayFor(model=>model.Nombre)<br />
    @Html.LabelFor(model=>model.Apellido) @Html.DisplayFor(model=>model.Apellido)<br />
    @Html.LabelFor(model=>model.Edad) @Html.DisplayFor(model=>model.Edad)<br />
    @Html.LabelFor(model=>model.Telefono) @Html.DisplayFor(model=>model.Telefono)<br />
    @Html.LabelFor(model=>model.Correo) @Html.DisplayFor(model=>model.Correo)<br />
    @Html.LabelFor(model=>model.Genero) @Html.DisplayFor(model=>model.Genero)<br />
    @Html.LabelFor(model=>model.Estado) @Html.DisplayFor(model=>model.Estado)<br />
    @Html.LabelFor(model=>model.Hobbys) @Html.DisplayFor(model=>model.Hobbys)

</div>

HtmlHelperTr/Views/Formulario/Index.cshtml
@using HtmlHelperTr.Models

@model Formulario

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<Form class="form-horizontal" method="post">

    <div class="form-group">
        @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Cedula, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Nombre, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Apellido, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Edad, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Telefono, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Correo, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Genero, new SelectList(Enum.GetValues(typeof(Gender))), "Seleciona el Genero", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-xs-4">
           @Html.RadioButtonFor(m => m.Estado, "Casado") @Html.Label("Casado")
           @Html.RadioButtonFor(m => m.Estado, "Soltero") @Html.Label("Soltero")
           @Html.RadioButtonFor(m => m.Estado, "Union Libre") @Html.Label("Union Libre")
           @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Hobbys, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.Hobbys, "Programar") @Html.Label("Programar")
            @Html.CheckBoxFor(model => model.Hobbys, "Jugar") @Html.Label("Jugar")
            @Html.CheckBoxFor(model => model.Hobbys, "Cantar") @Html.Label("Cantar")
            @Html.CheckBoxFor(model => model.Hobbys, "Bailar") @Html.Label("Bailar")

            @Html.ValidationMessageFor(model => model.Hobbys, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Index" class="btn btn-default" />
        </div>
    </div>
</Form>

HtmlHelperTr/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HtmlHelperTr/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HtmlHelperTr/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Bienvenido</h1>
</div>

<div class="form-horizontal">
    <button onclick="location.href='@Url.Action("Index","Formulario")'">Acceder &raquo;</button>
</div>

HtmlHelperTr/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>